<?php

namespace AppBundle\Repository;

/**
 * issuesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class issuesRepository extends \Doctrine\ORM\EntityRepository
{
}
