<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXcdbjjz\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXcdbjjz/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerXcdbjjz.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerXcdbjjz\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerXcdbjjz\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Xcdbjjz',
    'container.build_id' => '7ab10626',
    'container.build_time' => 1534060388,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerXcdbjjz');
